#!/usr/local/bin/python3

import sys
import bbcradio
from docopt import docopt

programmes = '''\
Accepted programmes:
    {}'''.format('\n    '.join(bbcradio.PROG_DICT.keys()))

usage = '''\
Usage:
    {name} url <programme>
    {name} details [--clean] <programme>

Options:
    --clean     Use two newlines instead of a pipe
                to separate the episode details

{prog_list}'''.format(name='beebhijack', prog_list=programmes)

args = docopt(usage)

if args['<programme>'] not in bbcradio.PROG_DICT:
    print('Given programme is not in the dictionary', file=sys.stderr)
    print(programmes, file=sys.stderr)
    sys.exit(-1)

episode_code = bbcradio.latest_episode_code(args['<programme>'])
if not episode_code:
    sys.stderr.write('Encountered problem fetching latest episode code\n')
    sys.exit(-1)

if args['url']:
    print(bbcradio.episode_player_url(episode_code))
elif args['details']:
    details = bbcradio.episode_details(episode_code)
    sep = '\n\n' if args['--clean'] else '|'
    joined = sep.join(details) + '\n'
    sys.stdout.buffer.write(joined.encode())
