#!/usr/local/bin/python3

import sys
import bbcradio
from docopt import docopt

programmes = '''\
Accepted programmes:
    {}'''.format('\n    '.join(bbcradio.PROG_DICT.keys()))

usage = '''\
Usage:
    {0} url <programme>
    {0} details <programme>

{1}'''.format(sys.argv[0], programmes)

args = docopt(usage)

if args['<programme>'] not in bbcradio.PROG_DICT.keys():
    print('Given programme is not in the dictionary', file=sys.stderr)
    print(programmes, file=sys.stderr)
    sys.exit(-1)

programme_code = bbcradio.PROG_DICT[args['<programme>']]
episode_code = bbcradio.latest_episode_code(programme_code)

if args['url']:
    print(bbcradio.episode_player_url(episode_code))
elif args['details']:
    details = bbcradio.fetch_episode_details(episode_code)
    print('|'.join(details))
