#!/usr/local/bin/python3

import logging
import logging.handlers
from pathlib import Path
import sys

import bbcradio
from docopt import docopt

logger = logging.getLogger('beebhijack')
logger.setLevel(logging.INFO)

file_handler = logging.handlers.RotatingFileHandler(
    Path('~/Library/Logs/robjwells/beebhijack.log').expanduser(),
    maxBytes=1024 * 1024,
    backupCount=5)
file_handler.setFormatter(
    logging.Formatter(
        '{asctime}  {name}  {levelname}  {message}',
        style='{',
        datefmt='%Y-%m-%d %H:%M',
    ))

console_handler = logging.StreamHandler()
console_handler.setLevel(logging.ERROR)
console_handler.setFormatter(
    logging.Formatter('{message}', style='{'))

logger.addHandler(file_handler)
logger.addHandler(console_handler)

programmes = '''\
Registered programmes:
    {}'''.format('\n    '.join(bbcradio.PROG_DICT.keys()))

usage = '''\
Usage:
    {name} url <programme>
    {name} details [--clean] <programme>

Options:
    --clean     Use two newlines instead of a pipe
                to separate the episode details

{prog_list}'''.format(name='beebhijack', prog_list=programmes)


def interface(argv):
    args = docopt(usage, argv=argv)

    programme = args['<programme>']
    if programme not in bbcradio.PROG_DICT:
        logger.error('{} is not a registered programme'.format(programme))
        docopt(usage, argv=['--help'])

    try:
        episode_code = bbcradio.latest_episode_code(args['<programme>'])
    except bbcradio.NoneAvailableError as e:
        logger.error(e)
        sys.exit(-1)

    if args['url']:
        print(bbcradio.episode_player_url(episode_code))
    elif args['details']:
        details = bbcradio.episode_details(episode_code)
        sep = '\n\n' if args['--clean'] else '|'
        print(sep.join(details))


if __name__ == '__main__':
    interface(sys.argv[1:])
